CREATE USER wsbarcode_user;
ALTER USER wsbarcode_user WITH ENCRYPTED PASSWORD 'wsbarcodepass';
COMMENT ON ROLE wsbarcode_user IS 'WSBarCode';
CREATE DATABASE wsbarcode_db;
GRANT ALL PRIVILEGES ON DATABASE wsbarcode_db TO wsbarcode_user;
COMMENT ON DATABASE wsbarcode_db IS 'WSBarCode';

\c wsbarcode_db
set role wsbarcode_user;

CREATE TABLE bc_algorithm (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(10) NOT NULL,
    in_pattern VARCHAR(30) NOT NULL,
    out_pattern VARCHAR(30) NOT NULL,
    description VARCHAR(200)
);

ALTER TABLE bc_algorithm 
ADD CONSTRAINT PK_bc_algorithm 
PRIMARY KEY (id);
    
ALTER TABLE bc_algorithm 
ADD CONSTRAINT UQ_bc_algorithm 
UNIQUE (name);

CREATE TABLE action (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    bc_algorithm_id INT NOT NULL,
    order_num INT NOT NULL,
    task VARCHAR(10) NOT NULL,
    ind1 INT,
    ind2 INT,
    count INT,
    description VARCHAR(200)
);

ALTER TABLE action 
ADD CONSTRAINT PK_action 
PRIMARY KEY (id);

CREATE TABLE client (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(10) NOT NULL,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200)    
);

ALTER TABLE client 
ADD CONSTRAINT PK_client 
PRIMARY KEY (id);
    
ALTER TABLE client 
ADD CONSTRAINT UQ_client 
UNIQUE (code);

CREATE TABLE client2algorithm (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    client_id INT NOT NULL,
    bc_algorithm_id INT NOT NULL,
    spec_value VARCHAR(15) NOT NULL
);

ALTER TABLE client2algorithm
ADD CONSTRAINT PK_client2algorithm
PRIMARY KEY (id);

ALTER TABLE client2algorithm
ADD CONSTRAINT UQ_client2algorithm
UNIQUE (client_id, bc_algorithm_id);

ALTER TABLE action
ADD CONSTRAINT FK_action_bc_algorithm
FOREIGN KEY (bc_algorithm_id) REFERENCES bc_algorithm (id);

ALTER TABLE client2algorithm
ADD CONSTRAINT FK_client2algorithm_algorithm 
FOREIGN KEY (bc_algorithm_id) REFERENCES bc_algorithm (id);

ALTER TABLE client2algorithm
ADD CONSTRAINT FK_client2algorithm_client 
FOREIGN KEY (client_id) REFERENCES client (id);