package com.example.j4roman.barcode.controller.utils;

import java.util.Collection;

/**
 * Invalid field format exception.
 * Generated by {@link BCValidator}
 */
public class BCInvalidFieldFormatException extends RuntimeException {

    private Collection<String> fieldList;

    public BCInvalidFieldFormatException(Collection<String> fieldList) {
        super("Fields values should be defined: " + fieldList.toString());
        this.fieldList = fieldList;
    }

    /**
     * @return list of field with invalid format
     */
    public Collection<String> getFieldList() {
        return this.fieldList;
    }
}
