package com.example.j4roman.barcode.controller.utils;

/**
 * This exceptions occurs in case of improper annotation usage
 * Generated by {@link BCValidator}
 */
public class BCValidateWrongClassException extends RuntimeException {

    public BCValidateWrongClassException(Class clazz) {
        super("The method does not work with class: " + clazz.getName());
    }
}
