package com.example.j4roman.barcode.controller.utils;


/**
 * The exception occurs in case of RTTI errors of checking process.
 * Generated by {@link BCValidator}
 */
public class BCWrongAnnotationUseException extends RuntimeException {

    public BCWrongAnnotationUseException(Throwable cause) {
        super(cause);
    }
}
