spring-datasource:
  driverClassName: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//host.docker.internal:1521/ORCLEDUDB
  username: MQ_DEV
  password: mqdev

hibernate-props:
  key-value:
    'hibernate.dialect': org.hibernate.dialect.Oracle12cDialect
    'hibernate.show_sql': true
    'current_session_context_class': org.springframework.orm.hibernate5.SpringSessionContext
    'hibernate.hbm2ddl.auto': none

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false